// actionTypes.js

export const LOGIN_START = 'LOGIN_START';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';


// Article action types
export const FETCH_ARTICLES_REQUEST = 'FETCH_ARTICLES_REQUEST';
export const FETCH_ARTICLES_SUCCESS = 'FETCH_ARTICLES_SUCCESS';
export const FETCH_ARTICLES_FAILURE = 'FETCH_ARTICLES_FAILURE';


export const ADD_ARTICLES_REQUEST = 'ADD_ARTICLES_REQUEST';
export const ADD_ARTICLES_SUCCESS = 'ADD_ARTICLES_SUCCESS';
export const ADD_ARTICLES_FAILURE = 'ADD_ARTICLES_FAILURE';

export const EDIT_ARTICLES_REQUEST = 'EDIT_ARTICLES_REQUEST';
export const EDIT_ARTICLES_SUCCESS = 'EDIT_ARTICLES_SUCCESS';
export const EDIT_ARTICLES_FAILURE = 'EDIT_ARTICLES_FAILURE';


// Categories action types
export const FETCH_CATEGORIES_REQUEST = 'FETCH_CATEGORIES_REQUEST';
export const FETCH_CATEGORIES_SUCCESS = 'FETCH_CATEGORIES_SUCCESS';
export const FETCH_CATEGORIES_FAILURE = 'FETCH_CATEGORIES_FAILURE';

export const ADD_CATEGORY_REQUEST = 'ADD_CATEGORY_REQUEST';
export const ADD_CATEGORY_SUCCESS = 'ADD_CATEGORY_SUCCESS';
export const ADD_CATEGORY_FAILURE = 'ADD_CATEGORY_FAILURE';

export const EDIT_CATEGORY_REQUEST = 'EDIT_CATEGORY_REQUEST';
export const EDIT_CATEGORY_SUCCESS = 'EDIT_CATEGORY_SUCCESS';
export const EDIT_CATEGORY_FAILURE = 'EDIT_CATEGORY_FAILURE';

// Commande action types
export const FETCH_COMMANDE_REQUEST = 'FETCH_COMMANDE_REQUEST';
export const FETCH_COMMANDE_SUCCESS = 'FETCH_COMMANDE_SUCCESS';
export const FETCH_COMMANDE_FAILURE = 'FETCH_COMMANDE_FAILURE';
