// Article action types
export const FETCH_ARTICLES_REQUEST = 'FETCH_ARTICLES_REQUEST';
export const FETCH_ARTICLES_SUCCESS = 'FETCH_ARTICLES_SUCCESS';
export const FETCH_ARTICLES_FAILURE = 'FETCH_ARTICLES_FAILURE';


export const FETCH_ARTICLESBYID_REQUEST = 'FETCH_ARTICLESBYID_REQUEST';
export const FETCH_ARTICLESBYID_SUCCESS = 'FETCH_ARTICLESBYID_SUCCESS';
export const FETCH_ARTICLESBYID_FAILURE = 'FETCH_ARTICLESBYID_FAILURE';


export const FETCH_CATEGORIES_REQUEST = 'FETCH_CATEGORIES_REQUEST';
export const FETCH_CATEGORIES_SUCCESS = 'FETCH_CATEGORIES_SUCCESS';
export const FETCH_CATEGORIES_FAILURE = 'FETCH_CATEGORIES_FAILURE';

// Commande action types
export const FETCH_COMMANDE_REQUEST = 'FETCH_COMMANDE_REQUEST';
export const FETCH_COMMANDE_SUCCESS = 'FETCH_COMMANDE_SUCCESS';
export const FETCH_COMMANDE_FAILURE = 'FETCH_COMMANDE_FAILURE';
